### ISSUE TITLE
Conditional Visibility depending on a toggle field

### ISSUE THREAD

**Issue by bnzo** [lara-zeus/bolt#100]
**Is your feature request related to a problem? Please describe.**
Conditional Visibility depending on a toggle field to avoid checkboxes or select

**Describe the solution you'd like**
A toogle field for a question like: `Do you like music?` Could make a text field `Which kind of music?`visible.

**Describe alternatives you've considered**
Using checkboxes or select, it works but it will be a nice to have.

**Additional context**
Thanks for this package! 👍

**Comment by atmonshi** [comment]
That sounds like a great option; I will look into it.

Thank you :)
