### ISSUE TITLE
Any plans to add signature field?

### ISSUE THREAD

**Issue by sanchezfranco** [lara-zeus/bolt#104]
Is your feature request related to a problem? Please describe.
Yes, the problem I'm facing is that the current form builder package does not include a "signature field" as an option. This is a crucial feature for my application as it requires users to provide their digital signatures.

Describe the solution you'd like
I would like to request the addition of a "signature field" in the form builder package. This field should allow users to input their digital signatures by either drawing on a canvas or uploading an image of their signature. The signature field should have options for customization, such as adjusting the size and color of the signature.

Describe alternatives you've considered
I have considered using external libraries or plugins to incorporate the signature functionality into the form builder. However, having this feature directly integrated into the form builder package would provide a more seamless and unified experience for developers and users.

Additional context
I believe that adding a signature field to the form builder package would greatly enhance its usability and make it more versatile for a wide range of applications. This feature would be particularly beneficial for forms that require user agreements, contracts, or any other document that requires a digital signature. Thank you for considering my feature request.

**Comment by atmonshi** [comment]
Thank you for the request :)

Currently, there is no plan to add more fields since the most common ones are already included, and I plan to keep the package as light as possible, with fewer dependencies.

But you can easily add your field:
https://larazeus.com/docs/bolt/v1/add-fields

Feel free to let me know if you need more info.
