### ISSUE TITLE
Thoughts on Filament V3 and time to complete?

### ISSUE THREAD

**Issue by jeremiahsherrill** [lara-zeus/bolt#105]
What do you think the time frame of filament v3 will be

**Comment by atmonshi** [comment]
the beta version is live now,
https://github.com/lara-zeus/bolt/releases

but hoping to finish the migration after the [release ](https://v3when.com/) of filament v3 stable version, hopefully wont be longer then aug the 5th.

**Comment by atmonshi** [comment]
I know I said the 5th, but currently, we facing two bugs :)

#7456, this will hopefully be fixed soon and only affects apps with more than one language.

#7485, this one is unfortunately related to Livewire, and I don't know when it will be fixed, and I can only release a stable version once it gets fixed.
This can cause the fields and sections to be deleted randomly, so we must wait for a fix.

**Comment by damms005** [comment]
Yes. Fixed: https://github.com/filamentphp/filament/issues/7485#issuecomment-1673556086

**Comment by atmonshi** [comment]
yes, just waiting for livewire to release the new release and for filament to support it and we are good to go :)

**Comment by atmonshi** [comment]
Finally 🚀 😃 a stable version.
tested as much as I can :) and all ✅

thank you everyone using Bolt.
please feel free to open a new issue if you have any questions or issues :).
