### ISSUE TITLE
Demo login error

### ISSUE THREAD

**Issue by damms005** [lara-zeus/bolt#108]
**Describe the bug**
Login to the bolt demo is not working.

**To Reproduce**
1. Go to https://demo.larazeus.com/admin/login
2. Click on 'Sign in'
3. See error 'These credentials do not match our records.'

**Expected behavior**
It should login to the bolt admin panel

**Screenshots**
![image](https://github.com/lara-zeus/bolt/assets/9839355/6bb8008d-18cc-4f3e-b55d-1092a461ac17)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by atmonshi** [comment]
thank you for let me know :)
it fixed now.
