### ISSUE TITLE
Ability to export form submissions

### ISSUE THREAD

**Issue by damms005** [lara-zeus/bolt#112]
**Is your feature request related to a problem? Please describe.**
Form submissions cannot be exported

**Describe the solution you'd like**
Form submissions should be exportable

**Additional context**
Seems like this can be helpful - https://github.com/pxlrbt/filament-excel#defining-columns

**Comment by atmonshi** [comment]
The export action was already there but disabled when upgrading to V3.
It will be enabled again in the next release.

**Comment by atmonshi** [comment]
add in [v2.0.0-beta13](https://github.com/lara-zeus/bolt/releases/tag/v2.0.0-beta13)
it's only available in "[Entries Report](https://demo.test/admin/responses/report?form_id=1)"
as a bulk action

<img width="1218" alt="Screenshot 2023-08-12 at 12 15 11 AM" src="https://github.com/lara-zeus/bolt/assets/1952412/75859096-d580-47fe-a298-cd7576b11dec">

Thank you for the report :)

**Comment by damms005** [comment]
It is either the Bolt version in the demo site not yet in the version v2.0.0-beta13 that contains this fix; or the Entries Report page is not easily accessible.

I am unable to find it in the demo.

**Comment by atmonshi** [comment]
the demo is on the last version, but I'll find a better place for it.

for now, you can access it from:
Forms->Entries->cog icon dropdown menu

<img width="1186" alt="Screenshot 2023-08-12 at 10 03 19 AM" src="https://github.com/lara-zeus/bolt/assets/1952412/6051c904-77b4-4da0-bea0-e92d05260db4">

**Comment by atmonshi** [comment]
I guess I posted the wrong link before :)
this is the correct one: https://demo.larazeus.com/admin/responses?form_id=1

**Comment by damms005** [comment]
> the demo is on the last version, but I'll find a better place for it.

+1 for this. 

Also, currently, you first have to click the cog icon (step 1), then the option you want to view (step 2). Will really be dope if you can make this a 1-click step rather than this current 2-click step.

**Comment by atmonshi** [comment]
Since there are multiple views for entries, making it one click is hard.
So far, I have come up with this idea:

<img width="452" alt="Screenshot 2023-08-12 at 7 33 34 PM" src="https://github.com/lara-zeus/bolt/assets/1952412/92586ca0-758e-42ff-939f-b46a374d8645">

And the button will be available on all pages for easy navigation.

**Comment by atmonshi** [comment]
will be released with #116

**Comment by Vbonnier** [comment]
Hi I got some issue with the export  

Call to a member function getRecord() on false {"userId":1,"exception":"[object] (Error(code: 0)

The issue seem to come from the ResponseExporter , is this occuring to anyone else ?

**Comment by atmonshi** [comment]
this issue a year old, please open a new one

and since its not happening in the demo:<https://demo.larazeus.com/admin/forms/feedback/report>
I dont have any idea
check the fields types and see which one causing the error

could it be that the form has no fields or responses?
