### ISSUE TITLE
Submission view not well formatted

### ISSUE THREAD

**Issue by damms005** [lara-zeus/bolt#113]
**Describe the bug**
When viewing for submissions e.g. https://demo.larazeus.com/admin/responses/21, select field does not indicate selected option

**To Reproduce**
1. Create a form. Ensure the form has one select dropdown option and set a collection for it to populate from
2. Open its view page and fill some data for it. Ensure to select an options for the Select dropdown option
3. Visit the responses view page e.g. https://demo.larazeus.com/admin/responses/21
4. Observe error that the select dropdown field does not indicate user selected option but rather dumps a json string of the collection, as shown in screenshot below

**Expected behavior**
The select dropdown field should indicate user selected option instead of a json string of the collection

**Screenshots**
![image](https://github.com/lara-zeus/bolt/assets/9839355/5ee6ebca-ee13-4e9c-9b23-4e4e3d5491a3)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Version 1.2.11

**Comment by atmonshi** [comment]
fixed in [v2.0.0-beta13](https://github.com/lara-zeus/bolt/releases/tag/v2.0.0-beta13)

thank you for the report :)
