### ISSUE TITLE
Route [bolt.forms.list] not defined

### ISSUE THREAD

**Issue by grafst** [lara-zeus/bolt#124]
**Describe the bug**
When navigating to the Forms List I get the error: `Route [bolt.forms.list] not defined.`
(The other routes .ie entries, categories work)

**To Reproduce**
1. composer require lara-zeus/bolt 
2. Add to AdminPanelProvider.php
3. php artisan vendor:publish --tag=zeus-bolt-migrations 
4. php artisan migrate
5. php artisan vendor:publish --tag=zeus-assets 
6. Go to https://xyz.test/admin/forms

**Expected behavior**
showing the list of forms

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 115

**Additional context**
https://flareapp.io/share/q5YWgJQP

**Comment by atmonshi** [comment]
what version are you using?
filament and bolt?

**Comment by atmonshi** [comment]
hope your issue has been fixed, feel free to reopen if not :)
