### ISSUE TITLE
Filament Resource form FormStatus model

### ISSUE THREAD

**Issue by aymanalhattami** [lara-zeus/bolt#125]
**Is your feature request related to a problem? Please describe.**
Form entries have only two static statues "new and closed", I need to add more statuses in addition to "new" and "closed". For example, I have Job Application Form created by bolt, so I need more status for the entries like: approved, not qualified and rejected.

I need to be able to manage and control all status.

I know that you use [calebporzio/sushi](https://github.com/calebporzio/sushi).

If you have any solution on how to add more statuses for FormStatus model, please tell me.

**Describe the solution you'd like**
I suggest to have a filament resource (list, create, edit and delete) for manage statues of bolt

**Comment by atmonshi** [comment]
Currently you can change the default status and use your own

https://larazeus.com/docs/bolt/v2/configuration

like:
```
->boltModels([
        'FormsStatus' => \App\Model\Models\FormsStatus::class,
    ])
```

> I suggest to have a filament resource (list, create, edit and delete) for manage statues of bolt

since status is just a state nothing much to it and I don't think you would change them that often :) I don't think it is worth making a resource.

But you can add it to your app since `FormsStatus` is just a sushi model.

**Comment by aymanalhattami** [comment]
It works,but there a need for some changes to use ```BoltPlugin::getModel('FormsStatus')``` instead of ```FormsStatus::query()->pluck('label', 'key')```

I will make a pull request

**Comment by atmonshi** [comment]
Thank you, I guess I missed a few places since I am always using the default status.
I'll check it and do a fix tomorrow if didn't beat me to it :).
