### ISSUE TITLE
Command to Publish Filament Resources

### ISSUE THREAD

**Issue by aymanalhattami** [lara-zeus/bolt#130]
**Is your feature request related to a problem? Please describe.**
It is good to have command for publish all filament resources. I need to make customization on FormResource

**Describe the solution you'd like**
1. solution 1: set filament resource in ```zeus-bolt.php``` config file in the same way as models.
```
'resources' => [
    'FormResource' => \LaraZeus\Bolt\Filament\Resources\FormResource::class,
    'CollectionResource' => \LaraZeus\Bolt\Filament\Resources\CollectionResource::class,
    'CategoryResource' => \LaraZeus\Bolt\Filament\Resources\CategoryResource::class,
    'ResponseResource' => \LaraZeus\Bolt\Filament\Resources\ResponseResource::class,
],
``` 

2. solution 2: make Laravel command to publish filament resources
```
php artisan lara-zeus-bolt:publish-filament-resources
```

**Comment by atmonshi** [comment]
What kind of changes are you looking for?
you can customize some of the options, like the icon and the group by overwriting it in the service provider like this

`FormResource::navigationIcon('heroicon-o-eye');`

check the file: `vendor/filament/filament/src/Resources/Resource.php` for all the available setters by filament.

**Comment by aymanalhattami** [comment]
I need to add some customize on ```FormResource``` form such as [set an active tab](https://filamentphp.com/docs/3.x/forms/layout/tabs#setting-the-default-active-tab), [Persisting the current tab in the URL's query string](https://filamentphp.com/docs/3.x/forms/layout/tabs#persisting-the-current-tab-in-the-urls-query-string), [Setting a tab icon](https://filamentphp.com/docs/3.x/forms/layout/tabs#setting-a-tab-icon), [Setting a tab badge](https://filamentphp.com/docs/3.x/forms/layout/tabs#setting-a-tab-badge) and other customizations for future

**Comment by atmonshi** [comment]
at this point, I recommend you copy the whole thing to your app :)

you're talking about these tabs correct?

![Screenshot 2023-08-21 103800](https://github.com/lara-zeus/bolt/assets/1952412/05676251-cb2c-40f7-b5c5-0cd8541237cd)

these are in another class not in the form resource so you will have to copy a lot of files to get the customization you need.

out of curiosity! Are you adding a tab badge to that tabs? what is the use case!?

**Comment by aymanalhattami** [comment]
> at this point, I recommend you copy the whole thing to your app :)

I'll make a fork, make  customization with my requirements and use the forked

> you're talking about these tabs correct?

yes



> these are in another class not in the form resource so you will have to copy a lot of files to get the customization you need.

yeah, I found  ```trait Schemata```

> out of curiosity! Are you adding a tab badge to that tabs? what is the use case!?

I need to add badge in tab for edit page to show if the form fields in this tab has been filled with data or not

**Comment by atmonshi** [comment]
> I need to add a badge in the tab for the edit page to show if the form fields in this tab have been filled with data or not

I think better to use the fork, this looks like a special case for your app.
however, I will make more options to customize the common things like resource icons, groups, etc.
