### ISSUE TITLE
[Bug]: Project running issue

### ISSUE THREAD

**Issue by shorifulislam00** [lara-zeus/bolt#140]
### What happened?

I just install the fresh copy of lara-zeus starter kit via `composer create-project Lara-zeus/zeus running`  command. Nicely installed. But while i login to admin and going to edit the form, i got error. 
![image](https://github.com/lara-zeus/bolt/assets/10585612/d632de9e-99b3-4314-8292-ed5d1f833391)

This error also in frontend. While going to open the form, it shows the error. 

I manually add this table in database, but yet it shows me error.

Would you like to explain me the issues ?

### How to reproduce the bug

Just run this command `composer create-project Lara-zeus/zeus running` and browse any forms in frontend. Login to admin and try to edit any form.

### Package Version

2.0

### PHP Version

8.1.10

### Laravel Version

10.15

### Which operating systems does with happen with?

Windows

**Comment by atmonshi** [comment]
Thank you for using the start kit and the report.

The table `forms_status` is not an actual mysql table. It uses SQLite database to populate the table and cache it.
for more:
https://github.com/calebporzio/sushi#how-it-works

It seems your environment doesn't have an SQLite database! can you check an let me know?!
in your terminal enter the command: `sqlite3`.

**Comment by atmonshi** [comment]
Also, a note: the starter kit is not upgraded to filament v3.
But still working on that, and hopefully, I'll release it soon.

**Comment by shorifulislam00** [comment]
Yes. I have sqlite3 installed on my pc and the version is 3.19.1

**Comment by shorifulislam00** [comment]
> Also, a note: the starter kit is not upgraded to filament v3. But still working on that, and hopefully, I'll release it soon.

I don't do anything. Just run the command of stater kit. No extra command.

One thing for your reference, Installation skipped in a point of process and show following error in command line.

`` 111/184 [================>-----------]  60%    Skipped installation of bin bin/paratest.bat for package brianium/paratest: name conflicts with an existing file``

I found paratest.bat file in `vendor/bin` and `vendor/brianium/paratest/bin`

Hope this information will help you to debug.

**Comment by atmonshi** [comment]
I honestly never had the issue before, so I am not sure.
One of the solutions is:

"Just delete the .sqlite file from /storage/framework/cache and try again!"

try searching for "SUSHI Error - could not find driver"

for ref:
https://stackoverflow.com/questions/51982770/could-not-find-driver-in-laravel
https://laracasts.com/discuss/channels/code-review/hard-time-solving-the-sushi-error

let me know how it goes and if I can do anything

**Comment by atmonshi** [comment]
`brianium/paratest` is from one of the dependencies I don't have control of it

and it is for dev will not affect the app

**Comment by shorifulislam00** [comment]
> I honestly never had the issue before, so I am not sure. One of the solutions is:
> 
> "Just delete the .sqlite file from /storage/framework/cache and try again!"
> 
> try searching for "SUSHI Error - could not find driver"
> 
> for ref: https://stackoverflow.com/questions/51982770/could-not-find-driver-in-laravel https://laracasts.com/discuss/channels/code-review/hard-time-solving-the-sushi-error
> 
> let me know how it goes and if I can do anything

Unfortunately no .sqlite file created under cache folder.

**Comment by atmonshi** [comment]
ok that's means laravel doesn't have access to the folder 
maybe it's a folder's permissions!
you should get a similar structure to this:

<img width="674" alt="Screenshot 2023-08-22 at 4 04 47 PM" src="https://github.com/lara-zeus/bolt/assets/1952412/20660973-d36e-42fa-860e-9082014dfb06">

you can also try to create the file
`sushi-lara-zeus-sky-models-post-status.sqlite`

**Comment by shorifulislam00** [comment]
> ok that's means laravel doesn't have access to the folder maybe it's a folder's permissions! you should get a similar structure to this:
> <img alt="Screenshot 2023-08-22 at 4 04 47 PM" width="674" src="https://user-images.githubusercontent.com/1952412/262360666-20660973-d36e-42fa-860e-9082014dfb06.png">
> 
> you can also try to create the file `sushi-lara-zeus-sky-models-post-status.sqlite`

Yes. i re-try and got the file. but still "could not find driver issue".

**Comment by atmonshi** [comment]
As I mentioned before, try searching for "SUSHI Error - could not find driver" and try the solutions.

also worth checking this one:
https://www.youtube.com/watch?v=VY8aaWphkBg

**Comment by shorifulislam00** [comment]
> As I mentioned before, try searching for "SUSHI Error - could not find driver" and try the solutions.
> 
> also worth checking this one: https://www.youtube.com/watch?v=VY8aaWphkBg

Ok. Thank you for your response

**Comment by atmonshi** [comment]
I wish I could do more :).

it's your environment, so I don't know about:

- operating system
- PHP version
- what extension you enabled in php
- apache or nginx
- etc...

You have to try and test till you find the issue.

As for the starter kit, I tried to install it on Mac and Windows but couldn't reproduce the issue. it always works fine.

let me know if I can do anything else.

**Comment by shorifulislam00** [comment]
> I wish I could do more :).
> 
> it's your environment, so I don't know about:
> 
>     * operating system
> 
>     * PHP version
> 
>     * what extension you enabled in php
> 
>     * apache or nginx
> 
>     * etc...
> 
> 
> You have to try and test till you find the issue.
> 
> As for the starter kit, I tried to install it on Mac and Windows but couldn't reproduce the issue. it always works fine.
> 
> let me know if I can do anything else.

Thanks for your effort. I got the issue. It's sqlite extension issue. It not enable for my apache. I enable it, and it worked fine. Thanks again.

**Comment by atmonshi** [comment]
That is great news, 
thank you for let me know the issue, I will add sqlite extension to the composer require.

**Comment by jimiero** [comment]
@atmonshi any other ideas why this happens?

i've checked and I do have sqlite extension enabled on php

also i see permissions are correct on **storage/framework/cache/sushi-lara-zeus-sky-models-post-status.sqlite** ( but there's nothing inside that file.

Interesting it works on local env but not on site server.

Any other tips how to check and make sure everything is oky ?

**Comment by jimiero** [comment]
@atmonshi found it,

I'll write here some tips for others who may have the issue to check:

1. Check and make sure the php version you have on your terminal cli, is the same version with the one used by apache/ngnix

2. Remove old sushi cache file so it can be regenerated, from:

storage/framework/cache/sushi-lara-zeus-sky-models-post-status.sqlite

In my case the issue was caused because in my server terminal I was having php8.3 while on apache it was using php8.2 which didn't had sqlite support enabled 🤦 

Good luck!

**Comment by atmonshi** [comment]
thank you @jimiero :)
