### ISSUE TITLE
[Bug]: Cannot submit new form

### ISSUE THREAD

**Issue by damms005** [lara-zeus/bolt#141]
### What happened?

Visit form page shows error:

```
Property type not supported in Livewire for property: [{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]
```

I also checked a demo form and got error https://demo.larazeus.com/bolt/diego

### How to reproduce the bug

Create new form
Visit the form view page
Error thrown:

```
Property type not supported in Livewire for property: [{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]
```

### Package Version

v2.0.1

### PHP Version

8.2.8

### Laravel Version

v10.20.0

### Which operating systems does with happen with?

Linux

### Notes

![image](https://github.com/lara-zeus/bolt/assets/9839355/23890d91-ebf9-4afa-940b-7f5569cbc1ca)

**Comment by atmonshi** [comment]
thank you for the report
I released a new version addressing this and will update the demo soon.
https://github.com/lara-zeus/bolt/releases/tag/v2.0.2

the issue is the HTML ID is required so I added a validation
but:
The error message is not shown since the field is on the inactive tab.
I will submit a bug report to Filament.

Thank you again

**Comment by atmonshi** [comment]
the demo is fixed now, feel free to reopen or create a  new issue if you still having issues :)

**Comment by damms005** [comment]
Can you provide a link to the bug report you submitted on Filament so I can follow it please?

**Comment by atmonshi** [comment]
I didn't have a chance to create a reproducing repo and submit a new issue, but there is one the same thing: [#7474](https://github.com/filamentphp/filament/issues/7474).

**Comment by damms005** [comment]
I think the errors are different. The error I reported is specifically a livewire error:

```
Property type not supported in Livewire for property: [{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]
```

**Comment by atmonshi** [comment]
it's not the same issue but related

The issue you mentioned is fixed [here](https://github.com/lara-zeus/bolt/pull/142/files#diff-ee1de356d4fc12f11e1ba62a5da50c39c224f6bae30d35ed12e860da82d38ec2R124)

The reason for the livewire issue is that I have:
```
$component->id($zeusField->options['htmlId'])
```
the `htmlId` is always required but there was no validation for it.

do you still having the same issue? tried the demo and the LW issue is fixed.

**Comment by damms005** [comment]
I created a reproduction repo that will help fix the bug: [https://github.com/damms005/example-app-bolt](https://github.com/damms005/example-app-bolt)

Login:
Username: test@test.com
Password: password

Please go through the [https://github.com/damms005/example-app-bolt#readme](readme) for steps on how to set up

**Comment by atmonshi** [comment]
thank you for doing this

I did clone and test

you need to go to /admin


http://127.0.0.1:8000/admin/forms/jupeb/edit
in the `Contact Information` section, the field `Email` doesn't have an htmlID:

<img width="301" alt="Screenshot 2023-08-27 at 1 42 20 PM" src="https://github.com/lara-zeus/bolt/assets/1952412/136b0835-1949-4e49-8af4-7aafb34d0b44">

if you write any random string, and save the form, then access it in the URL:
http://127.0.0.1:8000/custom-forms/jupeb

it will work 

<img width="1274" alt="Screenshot 2023-08-27 at 1 45 23 PM" src="https://github.com/lara-zeus/bolt/assets/1952412/70f39240-2237-4f7a-a7c8-97475df2b024">

**Comment by damms005** [comment]
I think there's a better way to communicate this. You know you may not be able to address this issue for every single person that has this error. Maybe throw a descriptive exception? Thoughts?

**Comment by atmonshi** [comment]
I did address this issue, I made a fix: https://github.com/lara-zeus/bolt/releases/tag/v2.0.2


and the issue of not been able to see the error message is related to this: https://github.com/filamentphp/filament/issues/7474

**Comment by damms005** [comment]
Got ya. This is an awesome package. Thanks my man.
