### ISSUE TITLE
[Bug]: add logo for category does not work

### ISSUE THREAD

**Issue by aymanalhattami** [lara-zeus/bolt#158]
### What happened?

Adding logo for category does not work

### How to reproduce the bug

I uploaded an image for category logo but nothing saved to database.

I also tried uploading a logo for category in [larazeus demo](https://demo.larazeus.com/admin/) and the same bug exists.

### Package Version

2.0.9

### PHP Version

8.1

### Laravel Version

10.21.1

### Which operating systems does with happen with?

Windows

**Comment by atmonshi** [comment]
Yes unfortunately there is a bug with that:
https://github.com/filamentphp/filament/issues/7591

And no one has a solution yet :)

only if you have multiple languages, set it to one language and it will work.

**Comment by atmonshi** [comment]
hi all, can you test this and confirm if it's working?

https://github.com/filamentphp/filament/pull/8432#issuecomment-1715654443

did a quick test, and seems to fix the issue.

**Comment by atmonshi** [comment]
This should be fixed with the last release from filament

and it fixed in the demo too
