### ISSUE TITLE
[Bug]: downgrading to v2.0.0-beta12 form v2.0.9 when run composer update command

### ISSUE THREAD

**Issue by aymanalhattami** [lara-zeus/bolt#161]
### What happened?

Package has been downgraded to v2.0.0-beta12

![larazeus-bolt](https://github.com/lara-zeus/bolt/assets/34315778/9ebff7b7-60c1-4b47-9d14-81b6bd24c9db)

### How to reproduce the bug

When I run composer update, package has been downgraded to v2.0.0-beta12.

It should be upgraded to v2.0.10

### Package Version

2.0.9

### PHP Version

8.1

### Laravel Version

10.22.0

**Comment by atmonshi** [comment]
sorry about that, due to some issues with `filament-export` I am using my own fork

You have to add to your composer:

```
"repositories": [
        {
            "type": "github",
            "url": "https://github.com/lara-zeus/filament-export"
        }
    ]
```

**Comment by aymanalhattami** [comment]
There is another package that support filament v3 and support Laravel queue

[Excel Export](https://filamentphp.com/plugins/pxlrbt-excel)

**Comment by atmonshi** [comment]
ya but `filament-export` includes preview, print, adding additional columns, PDF, CVS.... 

It's perfect, and no issues, except when using [filament modules](https://github.com/savannabits/filament-modules)

I'll PR it next week or so. Just a bit busy these days :)

dose adding the `repositories` to your composer work for you?

**Comment by aymanalhattami** [comment]
> dose adding the repositories to your composer work for you?

Still does not wok.

**Comment by atmonshi** [comment]
try removing `filament-export` from your composer
then `composer update -W`
also I think you need `"minimum-stability": "dev",`

**Comment by aymanalhattami** [comment]
It worked with me when I used the same branch of filament-excel as in the package

```json
"alperenersoy/filament-export": "dev-fix-there",

...

"repositories": [,
    {
        "type": "github",
        "url": "https://github.com/lara-zeus/filament-export"
    }
]
```
