### ISSUE TITLE
[Bug]: update translatable fields in form section resource and form field resource  

### ISSUE THREAD

**Issue by aymanalhattami** [lara-zeus/bolt#177]
### What happened?

When updating section 'name', the new value is updated for all locales in the database 

### How to reproduce the bug

I choose 'Arabic' form dropdown then updated the section 'name' field
![image](https://github.com/lara-zeus/bolt/assets/34315778/939b2ff0-b646-4c5d-84e1-696a2bfa6fe8)

This is how result stored in database
![image](https://github.com/lara-zeus/bolt/assets/34315778/0f88741c-394a-4c1f-8fd6-d9bb45ce01b7)

The true value should be like 👇
![image](https://github.com/lara-zeus/bolt/assets/34315778/dd645c4a-c25c-47e7-8574-a9a8987a3a82)

and the same issue when updating translatable field in field resource

### Package Version

2.0.17

### PHP Version

8.1

### Laravel Version

10.24.0

### Which operating systems does with happen with?

Windows

**Comment by atmonshi** [comment]
what filament version?

**Comment by aymanalhattami** [comment]
v3.0.54

**Comment by atmonshi** [comment]
already reported in filament [#8328](https://github.com/filamentphp/filament/issues/8328)

I will try next week but if you have the time to play around in the file
src/Resources/Pages/EditRecord/Concerns/Translatable.php:26

Detecting multi lang issues is just a headache :)

**Comment by aymanalhattami** [comment]
I will try as soon as I have time
