### ISSUE TITLE
Error view Form

### ISSUE THREAD

**Issue by XtrullorEas** [lara-zeus/bolt#198]
I had a problem creating the form, but then checking the repository I found that I had to create the compact column, this already works, after creating the form when I click on the form, where the metrics are, I get this error.

**could not find driver**
https://flareapp.io/share/KPgW4YZP

I would appreciate if there is a place where you can help me with this error, I have a lot of problems installing the bolt module as it is in the demo.

**Comment by atmonshi** [comment]
this is related to Redis and SQLite PHP extensions  
make sure they are enabled in your system
for more:
https://github.com/lara-zeus/sky/issues/161

let me know how it goes

**Comment by atmonshi** [comment]
Feel free to reopen if you have more issues :)
