### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by craigvc** [lara-zeus/bolt#222]
### What happened?

When trying to create a new field the user is unable to choose conditional field options till after the field is saved

### How to reproduce the bug

When trying to create a new field the user is unable to choose conditional field options till after the field is saved

### Package Version

2.1

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

macOS

**Comment by atmonshi** [comment]
thank you Craig, for the report and the support :)

this is a known limitation for the conditional visibility, I can't access other fields and their values when they haven't been saved to the DB yet.

I had some attempts to find better ways but none of them works perfectly

for now I can disable it and add a note if this can help you
and I will work on it to make it work in create form

thanks again.

**Comment by craigvc** [comment]
No dont delete it, we can just add a note to the user to save the record, though a thought though couldn't you autosave the record when the toggle is activated? or autosave to a temp table?

**Comment by atmonshi** [comment]
did a rewriteI for all sections and fields to be as modal.
this also fix the conditional visibility, instead reading the fields from the form instead from the DB.
 am still testing this, but so far all good.
and will be merge soon.

if you want to test it and give any feedback I appreciate it, you can use the branch #225

**Comment by atmonshi** [comment]
great news, this should be fixed with [v3](https://github.com/lara-zeus/bolt/releases/tag/v3.0.0), 
please notice that from now on you need filament v3.1
if you already there, the upgrade should be easy

feel free to open new issue if you have any bugs or more questions :)
