### ISSUE TITLE
[Bug]:  Composer cannot install bolt version ^3 

### ISSUE THREAD

**Issue by Pedynho** [lara-zeus/bolt#246]
### What happened?

when I try to install only bolt package the composer cannot resolve the others package dependencies.
That is the error mensage

"lara-zeus/bolt[v3.0.0, ..., v3.0.13] require alperenersoy/filament-export dev-fix-there -> found alperenersoy/filament-export[dev-main, v0.1.0-alpha, ..., v0.3.9, v3.0.0-beta, ..., v3.x-dev] but it does not match the constraint"

### How to reproduce the bug

using that composer packages

 "require": {
        "php": "^8.1",
        "bezhansalleh/filament-shield": "^3.1",
        "filament/filament": "^3.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    
    Try to run the composer require to install bolt
    
    composer require lara-zeus/bolt:3.0.13

### Package Version

^3

### PHP Version

8.2.7

### Laravel Version

^10.10

### Which operating systems does with happen with?

Linux

**Comment by atmonshi** [comment]
can you add this and see if it fix the issue
https://larazeus.com/docs/bolt/v3/getting-started/installation#content-note-about-filament-export

**Comment by Pedynho** [comment]
> can you add this and see if it fix the issue https://larazeus.com/docs/bolt/v3/getting-started/installation#content-note-about-filament-export

Root composer.json requires alperenersoy/filament-export dev-fix-there, found alperenersoy/filament-export[dev-main, v0.1.0-alpha, ..., v0.3.9, v3.0.0-beta, ..., v3.x-dev] but it does not match the constraint.

I think that version no exists anymore

**Comment by atmonshi** [comment]
it dose exist as a fork in my repo :)
https://github.com/lara-zeus/filament-export/tree/fix-there


you need to add the repo url:
```
require": {
  ...
  "alperenersoy/filament-export": "dev-fix-there",
},
"minimum-stability": "dev",
"prefer-stable": true,
"repositories": [
    {
        "type": "github",
        "url": "https://github.com/lara-zeus/filament-export"
    }
]
```

**Comment by Pedynho** [comment]
> it dose exist as a fork in my repo :) https://github.com/lara-zeus/filament-export/tree/fix-there
> 
> you need to add the repo url:
> 
> ```
> require": {
>   ...
>   "alperenersoy/filament-export": "dev-fix-there",
> },
> "minimum-stability": "dev",
> "prefer-stable": true,
> "repositories": [
>     {
>         "type": "github",
>         "url": "https://github.com/lara-zeus/filament-export"
>     }
> ]
> ```

It worked... Thank you soo mutch
