### ISSUE TITLE
Enhancing the filtering capabilities on custom Datasources

### ISSUE THREAD

**Issue by mohaphez** [lara-zeus/bolt#276]
Hi there !

At present, datasources utilize getModel to generate the required items, fetching all records of that model. 
However, there are scenarios where filtering records based on conditions is necessary, rather than displaying all records to the user. 
This implies that developers should have control over the query and be able to customize it. 

For instance, displaying records related to the logged-in user

Do you believe this is achievable?

**Comment by atmonshi** [comment]
fixed #277 
thanks for the PR :)
