### ISSUE TITLE
[Bug]: Files in 'file upload' field does not work

### ISSUE THREAD

**Issue by Pedynho** [lara-zeus/bolt#278]
### What happened?

When the 'file upload' input was used in any form, the file was not uploaded to the 's3' driver, for example. When we checked the response, the file was not available.

### How to reproduce the bug

use the file upload field ina form and try to upload and try to see the file attached.

### Package Version

^3

### PHP Version

8.2.7

### Laravel Version

^10.10

### Which operating systems does with happen with?

Linux

**Comment by atmonshi** [comment]
did you set the `uploadDisk` in the  configuration file?

[to publish the config](https://larazeus.com/docs/bolt/v3/getting-started/configuration#content-frontend-configuration)

**Comment by Pedynho** [comment]
Yes I didi it. It sounds like a permission error. For example, using the native Filament 3 upload input, I can pass the option ->visibility('private'). Without that option, the file features don't work. When I use the file upload feature of Bolt, there is an error accessing the object, and the file does not exist in the bucket, showing that the upload did not work

**Comment by atmonshi** [comment]
ok I will add the missing configuration for the file upload soon

**Comment by atmonshi** [comment]
can you test #280 and let me know.

change the composer to `"lara-zeus/bolt": "dev-upload-visibility",`

and add `'uploadVisibility' => 'public',` to your config

**Comment by Pedynho** [comment]
I've encountered a few issues with my app after update the package, but the most important one is related to file uploads to Amazon S3. When I set the visibility to 'public', the file doesn't upload to S3 at all. However, when I switch it to 'private', the file successfully uploads, but the URL generated to view the file in the app differs from the expected public URL format.

The URL in the app appears as:
https://s3.amazonaws.com/$bucket/$folder/$filename.jpg

I suspect the URL is missing a necessary signature or thing like taht on url query params for the user to be able to view the file.

Additionally, I am using the 'livewire:bolt.fill-form' tag component to display the form on my customized page.

**Comment by atmonshi** [comment]
I dont use S3 so I really cant test it.
other than the `disk ` , `directory ` and `visibility `

what other configuration you'll need for file upload with s3?

all changes in this file:
https://github.com/lara-zeus/bolt/pull/280/files#diff-6031be39b8f7227ff4654867bd180d179da8a6a4d5da4f81d94a5fff7d695c33

**Comment by atmonshi** [comment]
also I am using

```php
Storage::disk(config('zeus-bolt.uploadDisk'))->url($file)
```
to get the file url, check the file: `resources/views/filament/fields/file-upload.blade.php`

if you can debug around and let me know what I am missing!

thank you.

**Comment by Pedynho** [comment]
Good news... the 'UploadVisibility' solved the problem of uploading to S3.

To solve the visualization issue, I changed the published file 'file-upload.blade.php' as follows:

path to file: src/resources/views/vendor/zeus/filament/fields/file-upload.blade.php

```php

<div class="p-1 my-2 gap-2 flex">
    @foreach($responseValue as $file)
        <x-filament::button
            tag="a" target="_blank" size="sm" outlined
            href="{{ Storage::disk(config('zeus-bolt.uploadDisk'))->temporaryUrl($file, now()->addMinute()) }}">
            {{ __('view file') .': '. $loop->iteration }}
        </x-filament::button>
    @endforeach
</div>
```

**Comment by atmonshi** [comment]
great, so the change in the view can be done on the app url, since its diss from app to another.

I'll merge the PR. thank you.
