### ISSUE TITLE
Can I use other "users" table?

### ISSUE THREAD

**Issue by dkstudio86** [lara-zeus/bolt#320]
I need to use Users from a custom table/model. I have a custom user provider that login users from a custom model. In my case 'Afiliado' is a Authenticatable model associated with 'afiliados' table.

I want to config Bolt to use this model for register users anwers.

**Comment by atmonshi** [comment]
Bolt by default reads this config: `config('auth.providers.users.model')`
in `auth.php`

can you change it? or are you using both: `afiliados` and `users`?

**Comment by dkstudio86** [comment]
I'm using both models (User and Afiliado). I added a custom guard for Afiliado.

**Comment by atmonshi** [comment]
released on [v3.0.65](https://github.com/lara-zeus/bolt/releases/tag/v3.0.65).
please test and let me know.
