### ISSUE TITLE
Feature request for fields

### ISSUE THREAD

**Issue by RealMrHex** [lara-zeus/bolt#321]
Hey there, thanks for your advance and great package.

Can u add these please:

native field for date and datetime pickers
native, searchable fields to select box
default value for Toggle field

**Comment by atmonshi** [comment]
hey
`native` is understandable for devs, but it will be confusing for the end users. they wont get the different between them.

you can create any custom field, and use the current date time picker as starting point

the select is already have a searchable:
or I did'nt get your request.

<img width="411" alt="Screenshot 2024-08-22 at 8 35 34 PM" src="https://github.com/user-attachments/assets/e6846c2d-25e0-4198-a993-439b26cbbbbe">

also how "native and searchable will looks like?"

- the default value (for all) planned to be added on v4 or you can PR it if you like :)

**Comment by RealMrHex** [comment]
Gotcha, Thanks.
We can close this issue.
