### ISSUE TITLE
How to edit view frontend form ?

### ISSUE THREAD

**Issue by khairulimran-97** [lara-zeus/bolt#323]

**Comment by atmonshi** [comment]
can you provide more details to issue you're having?!

**Comment by khairulimran-97** [comment]
I want to add my own payment gateway, change logo, need to using my own blade view for all form. How to change UI on form submission?

**Comment by atmonshi** [comment]
check this updated [docs](https://larazeus.com/docs/bolt/v3/getting-started/assets#content-customizing-the-frontend-views)
