### ISSUE TITLE
[Bug]: Section name and fields name not changed after you change language value from top select box 

### ISSUE THREAD

**Issue by mohaphez** [lara-zeus/bolt#325]
### What happened?

Section name and fields name are not changed after change language value from top select box 
But i checked the database , values are saved correctly for other languages ,  But after edit and back again when you change the language value the section and fields name are not changed , just form name value changed

### How to reproduce the bug

Create the form  then edit it and change language value from select box and save new names for other language , then back and review it again , when you change the language value , the names still are English

### Package Version

3.0.65

### PHP Version

8.3.0

### Laravel Version

11.0

### Which operating systems does with happen with?

Linux

**Comment by atmonshi** [comment]
ya this known bug:

the section and fields are relations and wont work with translatable, and we cant find solution
<https://github.com/lara-zeus/translatable/issues/8>

**Comment by atmonshi** [comment]
I released a new version for an attempt to fix this issue
currently the demo working on the last version, if you want to test it.
https://demo.larazeus.com/admin/forms/en-1/edit


if its working as expected, you can use my fork of the plugin translatable, just add:
```json
{
    "type": "github",
    "url": "git@github.com:lara-zeus/translatable.git"
},
```

for now, the changes on [#9](https://github.com/lara-zeus/translatable/pull/9) will allow us to **store** uploaded files and relations, as long as we **save before** switching the local. (btw there is a shortcut on the forms (ctrl+s))

not prefect, yes. but at least now its usable.

next is working on persist the data when the user switch the local and store the other locals not only the active one.


will close this, feel free to reopen, or create a new one here or on the translatable repo :)
