### ISSUE TITLE
Route [blog] not defined when viewing a form.

### ISSUE THREAD

**Issue by khrnchn** [lara-zeus/bolt#36]
i have installed the bolt package to use the form builder. i can create form, however when i click on view it shows this error. 

```
Route [blogs] not defined.
```

is there any additional steps that i have to do after installing/ configuring the package?

**Comment by atmonshi** [comment]
Sorry about that; I forget a link in the core package.
You can now update to the last version or publish the view and customize it as you want.

Looking forward to your feedback.
