### ISSUE TITLE
Any Plans for Drag and Sort for the form fields?

### ISSUE THREAD

**Issue by jeremiahsherrill** [lara-zeus/bolt#46]
So far it looks like a pretty awesome form builder.  But wondering if there will be plans to add drag and sort functionality

**Comment by atmonshi** [comment]
Thank you for your feedback and support. I really appreciate it :).

The sorting for fields and sections is available:
![ezgif com-video-to-gif](https://github.com/lara-zeus/bolt/assets/1952412/76f62066-917b-4f65-8f11-0e83a0696680)

I hope this is what you were looking for!

**Comment by atmonshi** [comment]
Side note: as a sponsor, If you would like to show Your logo on the [homepage](https://larazeus.com), contact me at `info#larazeus.com`
Thank you again.

**Comment by jeremiahsherrill** [comment]
doh

**Comment by atmonshi** [comment]
For now, there is no straightforward way to customize the admin in general, and I don't like the idea of adding so many configurations to the config file.

But depending on the screen size, I will edit the columns to fit more per row.

**Comment by jeremiahsherrill** [comment]
Not so much just per row, but the ability to set 1 column full width 2 column, 3 column.  It doesn't ever have to it directly with inside there, just include a class in the options that would allow the users to define each form field themselves for layout purposes.

**Comment by atmonshi** [comment]
You mean the columns for rendering the form, right? Not on the admin page!
There is an option for `Section Column` It works well for all form layouts (page, wizard, tabs)

Also, there is an `HTML ID` for each field.
I will also add a class for each field, but it will be applied to the input itself, not the field container, which will be tricky.

Check the `Section Column` I hope it will be useful for your use case.

**Comment by jeremiahsherrill** [comment]
okay, just looking for ways it could be modified to make it easier for people to use.

**Comment by atmonshi** [comment]
I am happy to add more fungally and make the package extendable and customizable.
I need to understand the use case more so I can provide the best solution :)

I am still not sure is the request for the admin page or the frontend render forms?

**Comment by jeremiahsherrill** [comment]
Admin page for the users, so they can easily understand how things work

**Comment by atmonshi** [comment]
I will see after filament V3 to find more ways to customize the admin pages.
closing for now.
